FROM node:alpine
RUN apk add mysql mysql-client
# WORKDIR /app
# COPY ../backend/../services/../docker/./backend/package.json ./
# RUN npm install
# COPY ../backend/../services/../docker/./backend ./
# CMD ["npm", "run", "start:dev"]