version: "3.8"
services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: docker/services/frontend/Dockerfile
    volumes:
      - ./frontend:/var/frontend
    working_dir: /var/frontend
    ports:
      - "3000:3000"
  backend:
    networks:
      - edgex
    depends_on:
      - mysql
    container_name: backend
    build:
      context: .
      dockerfile: docker/services/backend/Dockerfile
    volumes:
      - ./backend:/var/backend
    working_dir: /var/backend
    ports:
      - "3001:3001"
  mysql:
    env_file: ./docker/environments/mysql.env
    networks:
      - edgex
    container_name: mysql
    image: mysql/mysql-server:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3307:3306"
    volumes:
      - /var/lib/mysql
networks:
  edgex:
