import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/layouts/top.module.scss";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Nest App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <aside className={styles.navigation}>
        <nav>
          <ul className={styles.lists}>
            <li className={styles.li}>list1</li>
            <li className={styles.li}>list2</li>
            <li className={styles.li}>list3</li>
            <li className={styles.li}>list4</li>
            <li className={styles.li}>list5</li>
          </ul>
        </nav>
        <div className={styles.sideFooter}>side footer</div>
      </aside>

      <main className={styles.main}>Main</main>
      <footer className={styles.footer}>Footer</footer>
    </div>
  );
};

export default Home;
