import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import axios from "axios";
import { useState } from "react";
import { useAuthDispatch } from "../context/auth";

const Home: NextPage = () => {
  const [value, setValue] = useState();
  const { jwt } = useAuthDispatch();

  const handleButton = async () => {
    console.log(jwt);
    const res = await axios.get(`${process.env.NEXT_PUBLIC_HOST}/users`, {
      headers: { Authorization: `Bearer ${jwt}` },
    });
    setValue(res.data);
    console.log(value);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Nest App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button onClick={handleButton}>Button</button>
      <p>{value}</p>
    </div>
  );
};

export default Home;
